### ISSUE TITLE
Set secret name dynamically through maven property not working

### ISSUE THREAD

**Issue by fedepia** [DecipherNow/vault-maven-plugin#10]
I am using this plugin in order to set properties that are going to be used by jooq. 

However, I need to dynamically setup the profile. When I execute `mvn spring-boot:run -Dspring.profiles.active=dev` the profile is not picked by maven-vault-plugin

This is the config I have:
```
<paths>
       <path>
              <name>secret/ctg-oms/${spring.profiles.active}</name>
```

Anyway, when I use a another variable like `profile`, and run `mvn spring-boot:run -Dprofile=dev` all works well with:
```
<paths>
       <path>
              <name>secret/ctg-oms/${profile}</name>
```

**Comment by joshua-rutherford** [comment]
This plugin doesn't perform any magic related to reading or setting maven properties that are not specifically listed in the mappings so I'm not exactly sure what is happening in this case.  Without more of your pom or your project this is really hard to troubleshoot.  If you cannot provide those, can you confirm the value of that property using the echo plugin:

```
 <build>
    <plugins>
      <plugin>
        <groupId>com.soebes.maven.plugins</groupId>
        <artifactId>echo-maven-plugin</artifactId>
        <version>0.3.0</version>
        <executions>
          <execution>
            <phase>initialize</phase>
            <goals>
              <goal>echo</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <echos>
            <echo>The value of spring.profiles.active is: ${spring.profiles.active}</echo>
          </echos>
        </configuration>
      </plugin>
    </plugins>
  </build>
```
Then run the following:
```
$ mvn spring-boot:run -Dspring.profiles.active=dev | grep "The value of spring.profiles.active is"
```
The expected output would be:
```
[INFO] The value of spring.profiles.active is: dev
```

**Comment by fedepia** [comment]
I have added this antrun to debug and the property was there, so I have re-tested everything again and looks to be working. Don't know what happened during the first tests but this looks like a wrong testing from my side.

I'll close this ticket carry on testing, in case I confirm this will back and re-open.
