### ISSUE TITLE
Skip vault maven plugin execution

### ISSUE THREAD

**Issue by fedepia** [DecipherNow/vault-maven-plugin#11]
Hi guys,

This is more a feature request than a bug.

We are using this plugin to pull properties from Vault and create properties for JOOQ. However, not in all mvn goals we need to run JOOQ, but the vault maven plugin is still executed.

In a Gitlab CI/CD process, we have multiple jobs and for them we explicitly need to disable plugin executions. Therefore, it would be a very important feature to add the capability to skip the vault maven plugin execution.

Similar way as we have `mvn clean package -DskipTests=true`, with would be great to have something like `mvn clean package -DskipVault=true`.

Is there any way to do it or this feature does not exist?

**Comment by joshua-rutherford** [comment]
It's not currently possible to turn it off if the phase it's tied to is executed.  It would be a trivial change to add that capability and we'd welcome a pull request.

**Comment by fedepia** [comment]
Joshua, I have no problem to do a pull request. Just cloned the project but looks like I'm missing moby-dns dependency from your private repo.
In addition, if you could bring some tips to implement this feature I could help.
On the other hand, if it is not possible to add this feature by myself, would you consider this feature request?

**Comment by joshua-rutherford** [comment]
That dependency was opensourced sometime ago and is available here: https://search.maven.org/artifact/com.deciphernow/moby-dns/1.0.0/jar.

I do not have time right now to address this as we have largely moved off using Maven and it would be of limited value to us.  However, I can tell you that the SureFire implementation of this is here:
https://github.com/apache/maven-surefire/blob/master/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L176.  It should be as simple as adding such a property to our base plugin mojo here: https://github.com/DecipherNow/vault-maven-plugin/blob/master/src/main/java/com/deciphernow/maven/plugins/vault/VaultMojo.java#L29

**Comment by fedepia** [comment]
Joshua, I've forked the project and sent a pull request although the CI is failing due to that lib.

**Comment by fedepia** [comment]
@joshua-rutherford alright, so changed the lib version as you said (removed snapshot), and the CI looks to be failing due to a Docker missing environment variable. 
Please, let me know if there is anything else I can do.

**Comment by fedepia** [comment]
@joshua-rutherford is there anything else from my side where I can help? What would be the next steps to for the release?

**Comment by joshua-rutherford** [comment]
It has been released via maven central and should be available soon. It make take some time to appear at the link below and even longer to be searchable.  Fortunately as soon as it appears in the link below you can start using.

https://mvnrepository.com/artifact/com.deciphernow/vault-maven-plugin

**Comment by fedepia** [comment]
Excellent! Thanks a lot for the hand. Let's wait then

**Comment by joshua-rutherford** [comment]
Yeah, things seem a bit slow on their end today.  I'm going to close this but feel free to open a new issue if you don't see the version 1.1.0 shortly.

**Comment by joshua-rutherford** [comment]
Just a heads up that the above link seems not to be showing the latest.  This one shows it as deployed: https://search.maven.org/search?q=a:vault-maven-plugin

**Comment by fedepia** [comment]
Great Joshua, I'm already using the new feature. Thanks a lot!

**Comment by joshua-rutherford** [comment]
No problem and thanks for the contribution.
