### ISSUE TITLE
Not working for vault running localhost:8200

### ISSUE THREAD

**Issue by fedepia** [DecipherNow/vault-maven-plugin#9]
I'm testing this plugin and it works well for a remote hosted vault, however when I try it with a localhost vault it is returning a 404.:
>[ERROR] Failed to execute goal com.deciphernow:vault-maven-plugin:1.0.0:pull (pull) on project myapp: Exception thrown pulling secrets. Vault responded with HTTP status code: 404 -> [Help 1]

This is how I started up my vault:
```
docker run -p 8200:8200 --name='vault' --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=mytoken' vault
```

And this is the plugin configuration:

```xml
<plugin>
                <groupId>com.deciphernow</groupId>
                <artifactId>vault-maven-plugin</artifactId>
                <version>1.0.0</version>
                <executions>
                    <execution>
                        <id>pull</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>pull</goal>
                        </goals>
                        <configuration>
                            <servers>
                                <server>
                                    <url>http://localhost:8200</url>
                                    <token>mytoken</token>
                                    <paths>
                                        <path>
                                            <name>secret/myapp</name>
                                            <mappings>
                                                <mapping>
                                                    <key>spring.datasource.username</key>
                                                    <property>env.DB_USER</property>
                                                </mapping>
                                                <mapping>
                                                    <key>spring.datasource.password</key>
                                                    <property>env.DB_PASSWORD</property>
                                                </mapping>
                                            </mappings>
                                        </path>
                                    </paths>
                                </server>
                            </servers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
Any clue why it isn't working?

Btw, I know my localhost vault is working because I'm loading properties correctly using the same configuration on `bootstrap.yml` in spring boot.

**Comment by joshua-rutherford** [comment]
A 404 suggests that the secret isn't in vault when the plugin tried to pull the secret.  My integration tests run on a local instance so there should be no issue there: https://github.com/DecipherNow/vault-maven-plugin/blob/master/src/test/java/com/deciphernow/maven/plugins/vault/IntTestVaults.java.

**Comment by fedepia** [comment]
@joshua-rutherford thanks for the response. 

My secrets exists because spring boot is loading them and they are being populated and my app works. However, I use your plugin in order to setup JOOQ properties.

Not sure if perhaps docker vault works differently?

I execute the following curl and it's working fine:
```
curl  --header "X-Vault-Token: mytoken" http://localhost:8200/v1/secret/data/myapp?version=1 
```

Notice that when creating the secret I created just `myapp` and put all the details.

**Comment by fedepia** [comment]
@joshua-rutherford, ok. Just found the problem.

I was running Vault through docker in `dev` mode. This was the command I executed:
```
docker run -p 8200:8200 --name='vault' --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=myroottoken' vault
```
When we run vault in dev mode it is automatically appending `/data` to the secrets, so the plugin works for vault running in server mode.

Thanks!
